name: Build GDExtension for Windows
on:
  workflow_dispatch:

env:
  LIBNAME: example

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows
            float-precision: single
            arch: x86_64
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
# Build
      - name: 🔗 GDExtension Build
        uses: ./.github/actions/build
        with:
          platform: ${{ matrix.platform }}
          arch: ${{ matrix.arch }}
          float-precision: ${{ matrix.float-precision }}
          build-target-type: template_release
      - name: Windows - Delete compilation files
        if: ${{ matrix.platform == 'windows' }}
        shell: pwsh
        run: |
          Remove-Item bin/* -Include *.exp,*.lib,*.pdb -Force
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: godot-cpp-template
          path: |
            ${{ github.workspace }}/bin/**
